# This is a basic workflow to help you get started with Actions

name: scheduler logs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  getSchedulerLogs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Create SSH key directory and add SSH key
        run: |
          mkdir -p ~/.ssh
          cd ~/.ssh
          ssh-keyscan -H 50.17.110.90 >> ~/.ssh/known_hosts
          touch bastion_host_ssh_key.pem
          echo "${{secrets.BASTION_HOST_SSH_KEY}}" >> bastion_host_ssh_key.pem
          chmod 600 bastion_host_ssh_key.pem
          touch trial_scheduler_ssh_pvt_key.pem
          echo "${{secrets.TRIAL_SCHEDULER_SSH_PVT_KEY}}" >> trial_scheduler_ssh_pvt_key.pem
          chmod 400 trial_scheduler_ssh_pvt_key.pem
          cat >> ~/.ssh/config <<END
          Host 50.17.110.90
            IdentityFile ~/.ssh/bastion_host_ssh_key.pem
            User ubuntu
            StrictHostKeyChecking no
            ForwardAgent yes
          END


      - name: getSchedulerLogs
        run: |
          cd ~/.ssh
          eval `ssh-agent -s`
          ssh-add trial_scheduler_ssh_pvt_key.pem
          ssh-add -L
          ssh 50.17.110.90 "ssh ubuntu@10.1.4.166 "docker logs --since 1h scheduler > ~/schedulerLogs""
          scp -i ~/key.pem -J ubuntu@50.17.110.90 -i ~/key.pem ubuntu@10.1.4.166:~/schedulerLogs ~/
